export const FETCH_PHONES_START = 'FETCH_PHONES_START';
export const FETCH_PHONES_SUCCESS = 'FETCH_PHONES_SUCCESS';
export const FETCH_PHONES_FAIL = 'FETCH_PHONES_FAIL';

export const SELECT_PHONE = 'SELECT_PHONE';

export const ADMIN_MODIFY_PHONE = 'MODIFY_PHONE';
export const SWITCH_ADMIN = 'SWITCH_ADMIN';

export const ADMIN_SAVE_PHONE_START = 'SAVE_PHONE_START';
export const ADMIN_SAVE_PHONE_SUCCESS = 'SAVE_PHONE_SUCCESS';
export const ADMIN_SAVE_PHONE_FAIL = 'SAVE_PHONE_FAIL';

export const ADMIN_DELETE_PHONE_START = 'ADMIN_DELETE_PHONE_START';
export const ADMIN_DELETE_PHONE_SUCCESS = 'ADMIN_DELETE_PHONE_SUCCESS';
export const ADMIN_DELETE_PHONE_FAIL = 'ADMIN_DELETE_PHONE_FAIL';

