export const FETCH_PHONES_START = 'FETCH_PHONES_START';
export const FETCH_PHONES_SUCCESS = 'FETCH_PHONES_SUCCESS';
export const FETCH_PHONES_FAIL = 'FETCH_PHONES_FAIL';

export const FETCH_INDIVIDUAL_PHONE_START = 'FETCH_INDIVIDUAL_PHONE_START';
export const FETCH_INDIVIDUAL_PHONE_SUCCESS = 'FETCH_INDIVIDUAL_PHONE_SUCCESS';
export const FETCH_INDIVIDUAL_PHONE_FAIL = 'FETCH_INDIVIDUAL_PHONE_FAIL';