export const FETCH_PHONES_START = 'FETCH_PHONES_START';
export const FETCH_PHONES_SUCCESS = 'FETCH_PHONES_SUCCESS';
export const FETCH_PHONES_FAIL = 'FETCH_PHONES_FAIL';

export const SELECT_PHONE = 'SELECT_PHONE';
export const MODIFY_PHONE = 'MODIFY_PHONE';

export const SAVE_PHONE_START = 'SAVE_PHONE_START';
export const SAVE_PHONE_SUCCESS = 'SAVE_PHONE_SUCCESS';
export const SAVE_PHONE_FAIL = 'SAVE_PHONE_FAIL';

export const FETCH_PHONE_IMAGE = 'FETCH_PHONE_IMAGE';

export const SWITCH_ADMIN = 'SWITCH_ADMIN';